// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EmailsController from "./emails_controller"
application.register("emails", EmailsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PersonController from "./person_controller"
application.register("person", PersonController)

import PruebaController from "./prueba_controller"
application.register("prueba", PruebaController)
